import React from "react";
import { motion } from "framer-motion";
import { Card, CardContent } from "@/components/ui/card";
import { Sparkles, BrainCircuit, TrendingUp, AlertTriangle } from "lucide-react";

export default function AiInsights() {
  const insights = [
    {
      title: "Unusual Spending Detected",
      description: "You spent 40% more on Dining this week compared to your 3-month average. Consider revisiting your lifestyle budget.",
      type: "alert",
      icon: <AlertTriangle className="h-6 w-6 text-amber-500" />
    },
    {
      title: "Savings Opportunity",
      description: "Based on your recurring subscriptions, canceling 'Netflix Premium' and 'Hulu' could save you $350 this year. You haven't used them in 30 days.",
      type: "opportunity",
      icon: <BrainCircuit className="h-6 w-6 text-violet-500" />
    },
    {
      title: "On Track for Vacation Goal",
      description: "At your current savings rate of 18%, you will hit your $3,000 Vacation Goal 2 months earlier than planned!",
      type: "success",
      icon: <TrendingUp className="h-6 w-6 text-green-500" />
    }
  ];

  return (
    <div className="space-y-8 animate-in fade-in duration-700 max-w-5xl mx-auto">
      <div className="flex flex-col gap-2">
        <h1 className="text-3xl font-bold tracking-tight text-[#0F1729] flex items-center gap-3">
          <Sparkles className="h-8 w-8 text-[#1565C0]" /> AI Insights
        </h1>
        <p className="text-sm text-[#5A6A8A]">Personalized financial intelligence generated by your FinFlow AI.</p>
      </div>

      <div className="grid grid-cols-1 gap-6">
        {insights.map((insight, idx) => (
          <motion.div 
            key={idx}
            initial={{ opacity: 0, y: 15 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: idx * 0.1 }}
          >
            <Card className="border-[#E8EEF8] shadow-sm hover:shadow-md transition-all rounded-[24px] bg-white overflow-hidden p-6 hover:border-[#1565C0]/30 cursor-default">
              <div className="flex items-start gap-4">
                <div className="h-12 w-12 rounded-xl bg-[#F5F9FF] border border-[#E8EEF8] flex items-center justify-center shrink-0 shadow-sm">
                  {insight.icon}
                </div>
                <div className="flex-1 space-y-1">
                  <h3 className="text-lg font-black text-[#0F1729] tracking-tight">{insight.title}</h3>
                  <p className="text-sm font-medium text-[#5A6A8A] leading-relaxed">{insight.description}</p>
                </div>
              </div>
            </Card>
          </motion.div>
        ))}
      </div>
      
      <div className="mt-8 p-6 rounded-[24px] finflow-gradient text-white flex flex-col md:flex-row items-center justify-between gap-6 shadow-xl shadow-blue-500/20">
        <div className="space-y-2 text-center md:text-left">
          <h3 className="text-xl font-black">Generate Deep Report</h3>
          <p className="text-sm font-medium opacity-90">Let AI scan your entire 12-month transaction history for tax deductions.</p>
        </div>
        <button className="h-12 px-8 bg-white text-[#1565C0] font-black rounded-xl shadow-sm hover:bg-white/90 transition-all shrink-0">
          Scan Now
        </button>
      </div>
    </div>
  );
}
